"""The machine-readable contract handed to a model-driven extractor.

Two artefacts per request, both generated rather than written by hand:

* :func:`proposal_schema` — a JSON Schema for the batch of proposals. Unit indices are
  constrained to the exact set the request offered, so a citation to unseen text is not
  merely rejected downstream but **unexpressible**: a structured-output API will not
  produce it. Every vocabulary is a closed enum, and every object sets
  ``additionalProperties: false``.
* :func:`render_instructions` — the prose contract, listing the units and stating what
  must not be attempted.

Generating both from the same definitions the parsers use is the point. A hand-written
prompt drifts from the code that validates its output, and the drift always favours the
looser side.
"""

from __future__ import annotations

from typing import Any

from policy_ir.enums import (
    CompilationIntent,
    Effect,
    Lifecycle,
    Modality,
    SemanticKind,
    SemanticRole,
)
from policy_ir.ids import SCHEMA_VERSION
from policy_ir.jsonschema import enum_defs, expression_defs

from .candidates import DECLARABLE_MISSING
from .offer import ExtractionRequest


def proposal_schema(request: ExtractionRequest) -> dict[str, Any]:
    """Build the JSON Schema for proposals against one request."""
    unit_indices = [unit.index for unit in request.units]
    unit_ref = {"type": "integer", "enum": unit_indices}
    defs: dict[str, Any] = {**enum_defs(), **expression_defs()}
    defs["RoleCitation"] = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "role": {"enum": [member.value for member in SemanticRole]},
            "units": {
                "type": "array",
                "minItems": 1,
                "uniqueItems": True,
                "items": unit_ref,
            },
        },
        "required": ["role", "units"],
    }
    defs["CandidateProposal"] = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "modality": {"enum": [m.value for m in Modality]},
            "semantic_kind": {"enum": [k.value for k in SemanticKind]},
            "effect": {"enum": [e.value for e in Effect]},
            "display_unit": unit_ref,
            "citations": {
                "type": "array",
                "minItems": 1,
                "items": {"$ref": "#/$defs/RoleCitation"},
            },
            "subject_ref": {"type": "string"},
            "action": {"type": "string"},
            "object_ref": {"type": "string"},
            "condition_ast": {"$ref": "#/$defs/Expression"},
            "effect_ast": {"$ref": "#/$defs/Expression"},
            "exception_ast": {"$ref": "#/$defs/Expression"},
            "temporal_constraint": {"$ref": "#/$defs/TemporalConstraint"},
            "scope": {"$ref": "#/$defs/Scope"},
            "effective_period": {"$ref": "#/$defs/EffectivePeriod"},
            "lifecycle": {"enum": [value.value for value in Lifecycle]},
            "compilation_intent": {"enum": [i.value for i in CompilationIntent]},
            "authority_ref": {"type": "string"},
            "cross_reference_targets": {"type": "array", "items": {"type": "string"}},
            "missing": {
                "type": "array",
                "items": {"enum": sorted(DECLARABLE_MISSING)},
                "uniqueItems": True,
            },
        },
        "required": ["modality", "semantic_kind", "effect", "display_unit", "citations"],
    }
    # Only the records a proposal may embed; the rest of the IR is not its business.
    for name in ("TemporalConstraint", "Scope", "ScopeDimension", "EffectivePeriod"):
        defs.setdefault(name, _record_stub(name))

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": f"Policy IR extraction proposals for {request.chunk_id}",
        "description": (
            "Zero or more proposed clauses for one chunk. Cite only the offered unit "
            "indices; the application builds every evidence span itself."
        ),
        "policyIrVersion": SCHEMA_VERSION,
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "candidates": {"type": "array", "items": {"$ref": "#/$defs/CandidateProposal"}}
        },
        "required": ["candidates"],
        "$defs": defs,
    }


def _record_stub(name: str) -> dict[str, Any]:
    """Schema for an IR record a proposal may embed, derived from the dataclass.

    Generated by the same code that generates the IR's own schema, so the two cannot
    describe the same record differently.
    """
    from policy_ir import models, scope
    from policy_ir.jsonschema import record_schema

    return record_schema(getattr(models, name, None) or getattr(scope, name))


#: What a proposal must never do. Stated in the instructions because a schema can forbid
#: a shape but not an intention.
PROHIBITIONS = (
    "Do not write FEEL, SQL, XML, JavaScript, Python or any other code. Expressions are "
    "built only from the closed grammar in this schema, and the compiler serialises them.",
    "Do not cite a unit that is not listed below. There is no other way to reference the "
    "document, and an index outside the list will be refused.",
    "Do not state a number, date or duration that does not appear in the units you cite. "
    "Every value is checked against the cited text.",
    "Do not invent an attribute, actor, threshold or process step that the units do not "
    "state. If a semantic field is not stated, name it in `missing` instead.",
    "Do not supply a field you have also named in `missing`; that is a contradiction and "
    "the proposal will be refused.",
    "Do not choose an identifier. Identity is derived from the cited units.",
    "Return an empty `candidates` list if these units state no requirement, decision, "
    "definition or process step. That is a valid and expected answer.",
)


def render_instructions(request: ExtractionRequest) -> str:
    """Render the prose contract for one request, listing its offered units."""
    lines = [
        f"# Extraction request for chunk {request.chunk_id}",
        "",
        f"Section: {request.section_path or '(none recorded)'}",
        f"Document: {request.document_id}",
        f"Policy IR version: {SCHEMA_VERSION}",
        "",
        "## Task",
        "",
        "Propose zero or more clauses supported by the numbered units below. For each "
        "clause, cite the units that support each part of it by index, and choose values "
        "only from the enumerated vocabularies in the accompanying JSON Schema.",
        "",
        "## Rules",
        "",
    ]
    lines.extend(f"{index}. {rule}" for index, rule in enumerate(PROHIBITIONS, start=1))
    lines.extend(["", "## Units", ""])
    for unit in request.units:
        lines.append(f"[{unit.index}] {unit.text}")
    return "\n".join(lines) + "\n"
