[pytest]
testpaths = tests
addopts =
    -q
    --cov
    --cov-report=term-missing
    --cov-report=html:coverage-html
    --cov-report=xml:coverage.xml
    --alluredir=allure-results
    --clean-alluredir
